# Generated by Django 6.0rc1 on 2025-11-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exception_class_path", models.TextField()),
                ("traceback", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("callable_path", models.CharField(max_length=255)),
                ("backend", models.CharField(max_length=200)),
                ("queue_name", models.CharField(max_length=100)),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("available_after", models.DateTimeField()),
                ("attempt_count", models.IntegerField(default=0)),
                ("takes_context", models.BooleanField(default=False)),
                ("arguments", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESSFUL", "Successful"),
                        ],
                        default="READY",
                        max_length=10,
                    ),
                ),
                ("enqueued_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("return_value", models.JSONField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_id", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField()),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("FAILED", "Failed"), ("SUCCESSFUL", "Successful")],
                        max_length=10,
                    ),
                ),
                (
                    "error",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt",
                        to="dbtasks.error",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="dbtasks.task",
                    ),
                ),
            ],
        ),
    ]
